### ISSUE TITLE
Poor Predictions

### ISSUE THREAD

**Issue by djhocking** [Conte-Ecology/conteStreamTemperature_northeast#10]
Most of the predictions are reasonable and validation shows them to be decent on average (RMSE = 1.9 on validation data). However, some predictions are terrible. In particular, there are many very negative predicted temperatures even when air temperature is well above 0 C. I think there are a variety of issues causing this rather than 1 single cause. Part of the problem is using a linear function to prediction a nonlinear process. However, since we are limiting predictions to the synchronized portion of the year this shouldn't be a major issue in theory. It should be rare for values to be negative and they should only occur when the air temperature is very negative during the beginning or end of the synchronized period.

One issue may be predicting outside the range of observations (extrapolation). There are conditions of precipitation, drainage area, and impoundments in the prediction space for which we have no observed data. This means the standardized values of these terms (especially their interactions) can be very highly positive or negative. 

Since these issues arise when doing 1.8 billion predictions (every stream reach daily from 1980 - 2013), it was challenging to find the cause of the problem. To diagnose it and understand when issues arise, I took the list of `featureid` which had predicted mean july temperatures to be < 5 C. Then I did daily predictions for those 104 catchments. 
1. I separated out the contributions from the fixed, site, huc, and year effects to see if it was a problem in a single part of the model. This didn't seem to be the case as strange predictions could arise from any part. Although it does seem like the fixed effects might be the biggest problem.
2. I looked at the standardized covariate values for the problem predictions and found that they were highly variable with standardized values ranging from -20, 20. This seems to be an issue of extrapolation with the biggest problem being with interactions, which means that combination of conditions not observed in the training (calibration) data occur and can drive the predictions into unrealistic extremes (since the model is linear). Precipitation values seem to be extreme but certainly not in all cases of bad predictions. Agriculture and herbaceous cover were also extreme in some cases.
3. When I looked at the original-scale covariate values on thing jumped out at me. `allonnet` was almost always over 70% when predictions were bad. I was using a quadratic `allonnet` term and that term interacted with air temperature as a fixed effect. This means that when the majority of the upstream drainage area is impounded the negative quadratic effect drives the predicted temperature extremely low. It also made me think that the percent impounded area makes sense to some extent but not as a quadratic since that was intended to allow different effects for very large and small dams. That makes sense if I multiple `allonnet` by the drainage area to get the actual impounded area.  One easy solution is to avoid predictions when `allonnet` is very high. I will probably do this since these streams will be very highly modified and likely aren't dominated by the same physical processes as our modeled sites. Additionally, there is a chance that some of these are higher than in reality due to imperfections of the delineation. 
4. One final observation was that some of the drainage areas were tiny (as small as 0.0009 $km^2$). Half of the bad predictions were at sites with drainage areas < 2 $km^2$. It's likely that many of the very smallest drainage areas are artificial in nature or if real could represent intermitent streams and streams with very different characteristics. Remember that this isn't just the drainage area of a point in the reach but actually the bottom of the reach. I think I will exclude sites with drainage areas < 1 $km^2$ from now on, just to be safe if nothing else.

**Comment by bletcher** [comment]
Good sleuthing!  Show me the details when I get back.

On Wednesday, September 23, 2015, Daniel J. Hocking <
notifications@github.com> wrote:

> Most of the predictions are reasonable and validation shows them to be
> decent on average (RMSE = 1.9 on validation data). However, some
> predictions are terrible. In particular, there are many very negative
> predicted temperatures even when air temperature is well above 0 C. I think
> there are a variety of issues causing this rather than 1 single cause. Part
> of the problem is using a linear function to prediction a nonlinear
> process. However, since we are limiting predictions to the synchronized
> portion of the year this shouldn't be a major issue in theory. It should be
> rare for values to be negative and they should only occur when the air
> temperature is very negative during the beginning or end of the
> synchronized period.
> 
> One issue may be predicting outside the range of observations
> (extrapolation). There are conditions of precipitation, drainage area, and
> impoundments in the prediction space for which we have no observed data.
> This means the standardized values of these terms (especially their
> interactions) can be very highly positive or negative.
> 
> Since these issues arise when doing 1.8 billion predictions (every stream
> reach daily from 1980 - 2013), it was challenging to find the cause of the
> problem. To diagnose it and understand when issues arise, I took the list
> of featureid which had predicted mean july temperatures to be < 5 C. Then
> I did daily predictions for those 104 catchments.
> 
>    1.
> 
>    I separated out the contributions from the fixed, site, huc, and year
>    effects to see if it was a problem in a single part of the model. This
>    didn't seem to be the case as strange predictions could arise from any
>    part. Although it does seem like the fixed effects might be the biggest
>    problem.
>    2.
> 
>    I looked at the standardized covariate values for the problem
>    predictions and found that they were highly variable with standardized
>    values ranging from -20, 20. This seems to be an issue of extrapolation
>    with the biggest problem being with interactions, which means that
>    combination of conditions not observed in the training (calibration) data
>    occur and can drive the predictions into unrealistic extremes (since the
>    model is linear). Precipitation values seem to be extreme but certainly not
>    in all cases of bad predictions. Agriculture and herbaceous cover were also
>    extreme in some cases.
>    3.
> 
>    When I looked at the original-scale covariate values on thing jumped
>    out at me. allonnet was almost always over 70% when predictions were
>    bad. I was using a quadratic allonnet term and that term interacted
>    with air temperature as a fixed effect. This means that when the majority
>    of the upstream drainage area is impounded the negative quadratic effect
>    drives the predicted temperature extremely low. It also made me think that
>    the percent impounded area makes sense to some extent but not as a
>    quadratic since that was intended to allow different effects for very large
>    and small dams. That makes sense if I multiple allonnet by the
>    drainage area to get the actual impounded area. One easy solution is to
>    avoid predictions when allonnet is very high. I will probably do this
>    since these streams will be very highly modified and likely aren't
>    dominated by the same physical processes as our modeled sites.
>    Additionally, there is a chance that some of these are higher than in
>    reality due to imperfections of the delineation.
>    4.
> 
>    One final observation was that some of the drainage areas were tiny
>    (as small as 0.0009 $km^2$). Half of the bad predictions were at sites with
>    drainage areas < 2 $km^2$. It's likely that many of the very smallest
>    drainage areas are artificial in nature or if real could represent
>    intermitent streams and streams with very different characteristics.
>    Remember that this isn't just the drainage area of a point in the reach but
>    actually the bottom of the reach. I think I will exclude sites with
>    drainage areas < 1 $km^2$ from now on, just to be safe if nothing else.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Conte-Ecology/conteStreamTemperature_northeast/issues/10
> .

## 

 Silvio O. Conte Anadromous Fish Research Center, U.S. Geological Survey
 P.O. Box 796 -- One Migratory Way
 Turners Falls, MA 01376
 (413) 863-3803
 Cell: (413) 522-9417
 FAX (413) 863-9810

ben_letcher@usgs.gov
bletcher@eco.umass.edu
http://www.lsc.usgs.gov/?q=cafb-research

**Comment by djhocking** [comment]
Reran the model without the `allonnet^2` term or it's interactions and there are a lot fewer spurious predictions.

**Comment by djhocking** [comment]
I was apparently getting an error from changing 

```
dplyr::filter(AreaSqKM < 200)
```

to

```
dplyr::filter(AreaSqKM >= 1 & AreaSqKM < 200 & allonnet < 70) # changed so don't deal with problematically small drainage areas (some were 0.00006 sq km) - for loop didn't like this!!!!!!!!!
```

probably because in some parallel iterations none of the catchments meet the criteria, resulting in an empty dataframe (or numeric(0)) which causes a problem with the output (results with different numbers of columns) because all iterations run based on my log file but the `foreach` function throws and error at the end.

I will have to do the additional filters post hoc. It should be okay because the revised code using dplyr and foreach reduced the time to do the predictions from 100 hours to 10 hours.
