### ISSUE TITLE
Outrageous Predictions

### ISSUE THREAD

**Issue by djhocking** [Conte-Ecology/conteStreamTemperature_northeast#4]
When I run the prediction function on the first 100 daymet featureid, I get mostly reasonable predictions, but some predictions for daily temperatures are over 40, 50, and even 100 C. I don't know if this is because of a mismatch in the model data (from old cleaned data from Kyle) and the data in the database or if it's just a problem of errors in the database since there hasn't been full QAQC yet.

Histogram of predictions clipped at 50C. This will mess up the derived parameters.

![prediction_histogram](https://cloud.githubusercontent.com/assets/2981696/5805057/99719dca-9fd9-11e4-93da-bac3f601aa75.png)

**Comment by djhocking** [comment]
I will also have to truncate predictions at 0C

**Comment by bletcher** [comment]
How do the parameter estimates look?

On Mon, Jan 19, 2015 at 12:51 PM, Daniel J. Hocking <
notifications@github.com> wrote:

> I will also have to truncate predictions at 0C
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Conte-Ecology/conteStreamTemperature_northeast/issues/4#issuecomment-70533937
> .

## 

 Silvio O. Conte Anadromous Fish Research Center, U.S. Geological Survey
 P.O. Box 796 -- One Migratory Way
 Turners Falls, MA 01376
 (413) 863-3803
 Cell: (413) 522-9417
 FAX (413) 863-9810

ben_letcher@usgs.gov
bletcher@eco.umass.edu
http://www.lsc.usgs.gov/?q=cafb-research

**Comment by djhocking** [comment]
There’s something still wrong. I just get NA for all the derived metrics. I’m trying to trouble shoot now.

---

Daniel J. Hocking

dhocking@unh.edumailto:dhocking@unh.edu
http://danieljhocking.wordpress.com/

---

On Jan 19, 2015, at 1:54 PM, Ben Letcher <notifications@github.com<mailto:notifications@github.com>> wrote:

How do the parameter estimates look?

On Mon, Jan 19, 2015 at 12:51 PM, Daniel J. Hocking <
notifications@github.commailto:notifications@github.com> wrote:

> I will also have to truncate predictions at 0C
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Conte-Ecology/conteStreamTemperature_northeast/issues/4#issuecomment-70533937
> .

## 

Silvio O. Conte Anadromous Fish Research Center, U.S. Geological Survey
P.O. Box 796 -- One Migratory Way
Turners Falls, MA 01376
(413) 863-3803
Cell: (413) 522-9417
FAX (413) 863-9810

ben_letcher@usgs.govmailto:ben_letcher@usgs.gov
bletcher@eco.umass.edumailto:bletcher@eco.umass.edu
http://www.lsc.usgs.gov/?q=cafb-research

**Comment by djhocking** [comment]
Sorry, misread the question. Parameter estimates are fine. They're still using the Kyle's data tables rather than pulling from the database.

I found the source of the NA in the derived metrics. It was just a bad filter in the very first line that set up the derived metric table. It worked for sites with data but not for unobserved sites. It's fixed now.

Looking catchment by catchment at the predictions, the predictions of temperatures of 260 C must come from bad data in the database. Maybe something stored as a 99 or -99 instead of NA or just missing data (NA or not) for a parameter that is critical. It is a small minority of catchments, so I will ignore them for now then later in the week check the values associated with featureid.

**Comment by walkerjeffd** [comment]
if you want to give me a list of featureids where the problems occur, I can
check the corresponding data in the database.

On Mon, Jan 19, 2015 at 4:06 PM, Daniel J. Hocking <notifications@github.com

> wrote:
> 
> Sorry, misread the question. Parameter estimates are fine. They're still
> using the Kyle's data tables rather than pulling from the database.
> 
> I found the source of the NA in the derived metrics. It was just a bad
> filter in the very first line that set up the derived metric table. It
> worked for sites with data but not for unobserved sites. It's fixed now.
> 
> Looking catchment by catchment at the predictions, the predictions of
> temperatures of 260 C must come from bad data in the database. Maybe
> something stored as a 99 or -99 instead of NA or just missing data (NA or
> not) for a parameter that is critical. It is a small minority of
> catchments, so I will ignore them for now then later in the week check the
> values associated with featureid.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Conte-Ecology/conteStreamTemperature_northeast/issues/4#issuecomment-70560716
> .

## 

Jeffrey D. Walker, PhD
http://walkerjeff.com

**Comment by djhocking** [comment]
Will do. Of the first 10 that I’m looking “735087” is the one giving bizarre estimates. Once I get the full list, I’ll send it along.

---

Daniel J. Hocking

dhocking@unh.edumailto:dhocking@unh.edu
http://danieljhocking.wordpress.com/

---

On Jan 19, 2015, at 4:08 PM, Jeff Walker <notifications@github.com<mailto:notifications@github.com>> wrote:

if you want to give me a list of featureids where the problems occur, I can
check the corresponding data in the database.

On Mon, Jan 19, 2015 at 4:06 PM, Daniel J. Hocking <notifications@github.com<mailto:notifications@github.com>

> wrote:
> 
> Sorry, misread the question. Parameter estimates are fine. They're still
> using the Kyle's data tables rather than pulling from the database.
> 
> I found the source of the NA in the derived metrics. It was just a bad
> filter in the very first line that set up the derived metric table. It
> worked for sites with data but not for unobserved sites. It's fixed now.
> 
> Looking catchment by catchment at the predictions, the predictions of
> temperatures of 260 C must come from bad data in the database. Maybe
> something stored as a 99 or -99 instead of NA or just missing data (NA or
> not) for a parameter that is critical. It is a small minority of
> catchments, so I will ignore them for now then later in the week check the
> values associated with featureid.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Conte-Ecology/conteStreamTemperature_northeast/issues/4#issuecomment-70560716
> .

## 

Jeffrey D. Walker, PhD
http://walkerjeff.com

**Comment by walkerjeffd** [comment]
Well that catchment (735087) is way up in northern maine, and so there
aren't any locations or data near there. Could be the covariate values?

On Mon, Jan 19, 2015 at 4:34 PM, Daniel J. Hocking <notifications@github.com

> wrote:
> 
> Will do. Of the first 10 that I’m looking “735087” is the one giving
> bizarre estimates. Once I get the full list, I’ll send it along.
> 
> ---
> 
> Daniel J. Hocking
> 
> dhocking@unh.edumailto:dhocking@unh.edu
> http://danieljhocking.wordpress.com/
> 
> ---
> 
> On Jan 19, 2015, at 4:08 PM, Jeff Walker <notifications@github.com<mailto:
> notifications@github.com>> wrote:
> 
> if you want to give me a list of featureids where the problems occur, I
> can
> check the corresponding data in the database.
> 
> On Mon, Jan 19, 2015 at 4:06 PM, Daniel J. Hocking <
> notifications@github.commailto:notifications@github.com
> 
> > wrote:
> > 
> > Sorry, misread the question. Parameter estimates are fine. They're still
> > using the Kyle's data tables rather than pulling from the database.
> > 
> > I found the source of the NA in the derived metrics. It was just a bad
> > filter in the very first line that set up the derived metric table. It
> > worked for sites with data but not for unobserved sites. It's fixed now.
> > 
> > Looking catchment by catchment at the predictions, the predictions of
> > temperatures of 260 C must come from bad data in the database. Maybe
> > something stored as a 99 or -99 instead of NA or just missing data (NA
> > or
> > not) for a parameter that is critical. It is a small minority of
> > catchments, so I will ignore them for now then later in the week check
> > the
> > values associated with featureid.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/Conte-Ecology/conteStreamTemperature_northeast/issues/4#issuecomment-70560716>
> > 
> > .
> 
> ## 
> 
> Jeffrey D. Walker, PhD
> http://walkerjeff.com
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/Conte-Ecology/conteStreamTemperature_northeast/issues/4#issuecomment-70560946>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Conte-Ecology/conteStreamTemperature_northeast/issues/4#issuecomment-70565032
> .

## 

Jeffrey D. Walker, PhD
http://walkerjeff.com

**Comment by djhocking** [comment]
Yeah, Kyle said there was missing data from northern ME because the catchments go into Canada but our data doesn’t. We’ll have to figure out how to handle that. Maybe at our meeting in February we can figure that out.

---

Daniel J. Hocking

dhocking@unh.edumailto:dhocking@unh.edu
http://danieljhocking.wordpress.com/

---

On Jan 19, 2015, at 4:46 PM, Jeff Walker <notifications@github.com<mailto:notifications@github.com>> wrote:

Well that catchment (735087) is way up in northern maine, and so there
aren't any locations or data near there. Could be the covariate values?

On Mon, Jan 19, 2015 at 4:34 PM, Daniel J. Hocking <notifications@github.com<mailto:notifications@github.com>

> wrote:
> 
> Will do. Of the first 10 that I’m looking “735087” is the one giving
> bizarre estimates. Once I get the full list, I’ll send it along.
> 
> ---
> 
> Daniel J. Hocking
> 
> dhocking@unh.edumailto:dhocking@unh.edumailto:dhocking@unh.edu
> http://danieljhocking.wordpress.com/
> 
> ---
> 
> On Jan 19, 2015, at 4:08 PM, Jeff Walker <notifications@github.com<mailto:notifications@github.com><mailto:
> notifications@github.com<mailto:notifications@github.com>>> wrote:
> 
> if you want to give me a list of featureids where the problems occur, I
> can
> check the corresponding data in the database.
> 
> On Mon, Jan 19, 2015 at 4:06 PM, Daniel J. Hocking <
> notifications@github.commailto:notifications@github.commailto:notifications@github.com
> 
> > wrote:
> > 
> > Sorry, misread the question. Parameter estimates are fine. They're still
> > using the Kyle's data tables rather than pulling from the database.
> > 
> > I found the source of the NA in the derived metrics. It was just a bad
> > filter in the very first line that set up the derived metric table. It
> > worked for sites with data but not for unobserved sites. It's fixed now.
> > 
> > Looking catchment by catchment at the predictions, the predictions of
> > temperatures of 260 C must come from bad data in the database. Maybe
> > something stored as a 99 or -99 instead of NA or just missing data (NA
> > or
> > not) for a parameter that is critical. It is a small minority of
> > catchments, so I will ignore them for now then later in the week check
> > the
> > values associated with featureid.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/Conte-Ecology/conteStreamTemperature_northeast/issues/4#issuecomment-70560716>
> > 
> > .
> 
> ## 
> 
> Jeffrey D. Walker, PhD
> http://walkerjeff.com
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/Conte-Ecology/conteStreamTemperature_northeast/issues/4#issuecomment-70560946>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Conte-Ecology/conteStreamTemperature_northeast/issues/4#issuecomment-70565032
> .

## 

Jeffrey D. Walker, PhD
http://walkerjeff.com
