### ISSUE TITLE
Error in breakpoints script

### ISSUE THREAD

**Issue by djhocking** [Conte-Ecology/conteStreamTemperature_northeast#7]
I am getting the following error when running the `breakpoints.R` script. There are a ton of nested `if()` statements and `for()` loops. This makes it hard for me to trouble shoot, especially since I didn't do any of the original coding.

```
[1] "BP 1 and 3" "4"          "674"        "2007"      
Error in `[<-.data.frame`(`*tmp*`, i, ii, value = c(1, 1)) : 
  replacement has 2 rows, data has 1
```

https://github.com/Conte-Ecology/conteStreamTemperature_northeast/blob/master/breakpoints.R

I will send Kyle the data that goes into this, generated via `retrieve_db.R` which takes ~5 hours to run.

**Comment by djhocking** [comment]
The only thing that has changed is that the data is being pulled in and organized from the database rather than from Kyle's csv. It might be worth starting by looking at the data structure (e.g. NA, data types, column names, matrix vs dataframe, unclass dplyr tbl, etc.). Also checking for any hard coding of lengths or dimensions.

**Comment by Tom-Bombadil** [comment]
When I try to read the `climateData.RData` from '/conte/home/kyle/Northeast_Data' I get the following error:

"Error: bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning message:
file ‘climateData.RData’ has magic number 'X'
  Use of save versions prior to 2 is deprecated 
During startup - Warning message:
unable to restore saved data in C:\KPONEIL\streamTemperature\climateData.RData"

Can you check this out when you get a chance so I can run the breakpoint script?

**Comment by walkerjeffd** [comment]
that usually means its an RDS file, try:

``` r
climateData <- readRDS('climateData.RData')
```

**Comment by Tom-Bombadil** [comment]
I was using `readRDS` and it still failed. That error was: 
"Error in readRDS(climateData_file) : error reading from connection"

Dan and I just discussed it and think maybe it was an error with the transfer or saving. He has figured out the issue with the script though so I don't think we need to worry about it.
